name: deploy-test-pypi

on:
  push:
    branches:
      - release/*

defaults:
  run:
    shell: bash

jobs:

  release:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: apt-get update -yqq && apt-get install -yqq curl

    - name: Install Task
      run: curl -sSfL https://taskfile.dev/install.sh | sh -s -- -b /usr/local/bin

    - name: Set PATH
      run: export PATH=/usr/local/bin:$PATH

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Set up the cache
      uses: actions/cache@v1
      with:
        path: .venv
        key: release-venv-cache

    - name: Setup Poetry
      uses: Gr1N/setup-poetry@v4

    - name: Setup project
      run: task setup
    
    - name: Test and Coverage
      run: |
        task test
        task coverage

    - name: Build
      run: task build

    - name: Set test-pypi repo
      run: poetry config repositories.testpypi https://test.pypi.org/legacy/

    - name: Publish Package
      run: poetry publish --username __token__ --password ${{ secrets.TEST_PYPI_TOKEN }} -r testpypi

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        path_to_write_report: ./codecov_report.gz
    
