name: ci

on:
  push:
    branches: ['*', '*/*']
  pull_request:
    branches: ['*', '*/*']

defaults:
  run:
    shell: bash

env:
  LANG: "en_US.utf-8"
  LC_ALL: "en_US.utf-8"
  POETRY_VIRTUALENVS_IN_PROJECT: "true"
  PYTHONIOENCODING: "UTF-8"

jobs:

  quality:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt-get update -yqq && sudo apt-get install -yqq curl

    - name: Install Task
      run: curl -sSfL https://taskfile.dev/install.sh | sh -s -- -b /usr/local/bin

    - name: Set PATH
      run: export PATH=/usr/local/bin:$PATH

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Set up the cache
      uses: actions/cache@v1
      with:
        path: .venv
        key: quality-venv-cache

    - name: Setup Poetry
      uses: Gr1N/setup-poetry@v4

    - name: Setup project
      run: task setup

    - name: Test
      run: task test

    - name: Coverage
      run: task coverage

    - name: Check if the documentation builds correctly
      run: task check-docs

    - name: Check the code quality
      run: task check-code-quality

    - name: Check if the code is correctly typed
      run: task check-code-types

    - name: Check for vulnerabilities in dependencies
      run: task check-code-deps

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        env_vars: OS,PYTHON
        fail_ci_if_error: true
        path_to_write_report: ./codecov_report.gz
